// Generates src/fonts.css: the IBM Plex fonts as embedded (base64 woff2) @font-face rules,
// so no version of the editor needs to download fonts. Run with `npm run fonts`.
import { readFile, writeFile } from 'node:fs/promises';

const FONTS = [
  ['IBM Plex Sans', 'ibm-plex-sans', [400, 500, 600]],
  ['IBM Plex Sans Condensed', 'ibm-plex-sans-condensed', [400, 500, 600]],
  ['IBM Plex Mono', 'ibm-plex-mono', [500, 600]],
];

export async function fontFaces() {
  let css = '/* IBM Plex (SIL Open Font License 1.1), latin subset, generated by scripts/fonts.js */\n';
  for (const [family, pkg, weights] of FONTS) {
    for (const w of weights) {
      const data = await readFile(`node_modules/@fontsource/${pkg}/files/${pkg}-latin-${w}-normal.woff2`);
      css += `@font-face{font-family:"${family}";font-style:normal;font-weight:${w};font-display:swap;src:url(data:font/woff2;base64,${data.toString('base64')}) format("woff2")}\n`;
    }
  }
  return css;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const css = await fontFaces();
  await writeFile('src/fonts.css', css);
  console.log(`src/fonts.css (${(css.length / 1024).toFixed(0)} KB)`);
}
